### ISSUE TITLE
Extending https://redis.uptrace.dev/ to be more verbose

### ISSUE THREAD

**Issue by shadowshot-x** [go-redis/docs#6]
We should plan to extend https://redis.uptrace.dev/ to be more descriptive about Redis commands, handling errors and understanding command outputs like status. It is overwhelming for someone who jumps straight to `go-redis` without going over the redis commands. It would be motivating to have all the commands, existing functionality and examples at the same place on the official documentation website. ( I know about https://pkg.go.dev/github.com/go-redis/redis and we can extend the website to include instructions in that format)

**Comment by shadowshot-x** [comment]
I can help with this issue if this is in scope with the project.

**Comment by vmihailenco** [comment]
There are 100+ Redis commands. Do you suggest to create 100 pages with documentation and examples? That is a lot of work to be done...

Creating a separate page for a group of commands sounds more approachable, for example, a separate page describing commands that work with Redis Set. Even that is several days of work to cover most popular Redis commands...

**Comment by shadowshot-x** [comment]
I was suggesting a group of commands but I agree it is a mammoth task
